/**
 * Customer Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InlineResponse2001Conditions {
    name: InlineResponse2001Conditions.NameEnum;

    value: number;

}
export namespace InlineResponse2001Conditions {
    export enum NameEnum {
        MinWidth = <any> 'minWidth',
        MaxWidth = <any> 'maxWidth',
        MinHeight = <any> 'minHeight',
        MaxHeight = <any> 'maxHeight'
    }
}
