/**
 * Customer Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface LoginError {
    error?: LoginError.ErrorEnum;

}
export namespace LoginError {
    export enum ErrorEnum {
        UserNotFound = <any> 'user_not_found',
        PasswordError = <any> 'password_error'
    }
}
