<?php

/**
 * Customer Portal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Customer Portal
 * @version 0.1
 */

$app->get('/', function () use ($app) {
    return $app->version();
});

/**
 * POST loginPost
 * Summary: 
 * Notes: Login with username and password. The response contains a JWT. 
 * Output-Formats: [application/json]
 */
$app->POST('/api/v1/login', 'DefaultApi@loginPost');
/**
 * POST logoutPost
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->POST('/api/v1/logout', 'DefaultApi@logoutPost');
/**
 * GET projectsGet
 * Summary: 
 * Notes: list of projects
 * Output-Formats: [application/json]
 */
$app->GET('/api/v1/projects', 'DefaultApi@projectsGet');
/**
 * GET projectsIdGet
 * Summary: 
 * Notes: project data
 * Output-Formats: [application/json]
 */
$app->GET('/api/v1/projects/{id}', 'DefaultApi@projectsIdGet');

